[package]
authors = ["bRad <brad@humanenginuity.com>"]
name = "cryptopals"
version = "0.1.0"

[dependencies]

[dependencies.fluent_validator]
git = "https://github.com/U-007D/fluent_validator.git"
optional = false

[profile]

[profile.release]
lto = true
opt-level = 3
